server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: khoa-spring-skeleton
  
  # H2 Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 Console (accessible at http://localhost:8080/api/h2-console)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA/Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  
  # SQL initialization
  sql:
    init:
      mode: always

# MyBatis configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.skeleton.model
  configuration:
    map-underscore-to-camel-case: true

# JWT configuration
jwt:
  secret: myVerySecretKeyForJWTTokenGenerationThatIsLongEnough
  expiration: 86400000 # 24 hours in milliseconds

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.example.skeleton: DEBUG
    org.springframework.security: DEBUG